performance updates
Hamerite/HyperDrive pull request #60
Opened 2021-11-04 18:53 UTC by ATepylo

Updated player script to use collider triggers rather than raycasts
changes to player prefab, asteroid prefabs, and player collision controller
minor changes to hit explosions

2021-11-04 19:15 UTC, Hamerite requested changes

2021-11-04 19:15 UTC, Hamerite commented on Assets/2_MainScene/S2_Scripts/S2_Gameplay/ParticleCleanup/HitExplosionCleanup.cs
> +        //transform.Translate(Vector3.back * S2_PoolController.Instance.GetSpeed() * Time.deltaTime);
If this is meant to be commented out the update function should probably just be removed, we don't need it to be checking for !hitObstacle if the method is empty

Also I can't remember exactly why but the explosion was moving with the object for some reason and not being parented, do the explosions function properly over moderate play time?

2021-11-04 19:15 UTC, Hamerite commented on Assets/2_MainScene/S2_Scripts/S2_PlayerScripts/S2_PlayerCollisionController.cs
> +        if((playerStatus[0] && playerStatus[1] && !playerStatus[2]))
A return instead of a gate should be used here

2021-11-04 19:15 UTC, Hamerite commented on Assets/2_MainScene/S2_Scripts/S2_PlayerScripts/S2_PlayerCollisionController.cs
> +        //if (!playerStatus[0] || !playerStatus[1] || playerStatus[2]) return;
We're never going to be going back to this code, might as well delete it fully instead of commenting it out

2021-11-04 19:15 UTC, Hamerite commented on Assets/2_MainScene/S2_Scripts/S2_PlayerScripts/S2_PlayerCollisionController.cs
> +                print("damaged");
Removal of un-needed console logs required

2021-11-04 19:15 UTC, Hamerite commented on Assets/2_MainScene/S2_Scripts/S2_PlayerScripts/S2_PlayerCollisionController.cs
> +            if (collision.gameObject.layer == 10 || collision.gameObject.layer == 11 || collision.gameObject.layer == 12) { S2_HUDUI.Instance.SetScore(collision.gameObject.layer - 9); print("safe zon
Console log

2021-11-04 19:58 UTC, Revolver1388 submitted a review, later dismissed

2021-11-04 20:24 UTC, Hamerite approved these changes

2021-11-05 18:11 UTC, Revolver1388 approved these changes

2021-11-05 18:11 UTC, merged